//===- bert_int8_matmul.cc -------------------------------------*- C++ -*-===//
//
// bionpu — AIE2P-accelerated genomics with reference-equivalence verification.
// Copyright (C) 2026 OpenSensor / Matt Davis <matt@opensensor.io>
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
// AIE2P compute-tile kernel — INT8 × INT8 → INT8 matmul with fused
// FP32 per-output-channel scale and INT8 saturation. Specializations
// per variant:
//
// * `bert_int8_matmul_<N>`         — head-style single-tile entry point.
//                                     The trailing `<N>` is the output
//                                     channel count, which differs across
//                                     callers:
//                                       v0.4-alpha head:  N=2  (`bert_int8_matmul_2`)
//                                       Phase-0 step 0.3b:
//                                         Q·Kᵀ per-head:  N=47 (`bert_int8_matmul_47`)
//                                         scores·V per-head: N=64 (`bert_int8_matmul_64`)
//                                     The symbol name is generated by token-
//                                     pasting BIONPU_BERT_N (set by the
//                                     Makefile -DBIONPU_BERT_N=<N>) onto
//                                     a `bert_int8_matmul_` prefix, so a
//                                     single source compile produces the
//                                     correct symbol for each shape.
//
// * `bert_int8_matmul_qkvo_init`   — qkvo v0.4-beta init: zero the static
//                                     INT32 accumulator on each tile.
// * `bert_int8_matmul_qkvo_acc`    — qkvo v0.4-beta accumulate: i32 +=
//                                     i8 × i8 over a single K_CHUNK slice
//                                     of x and the full output-channel
//                                     weight slab.
// * `bert_int8_matmul_qkvo_finalize` — qkvo v0.4-beta finalize: fused
//                                     FP32 scale + INT8 saturate of the
//                                     i32 accumulator into the int8
//                                     output partial.
//
// All entry points live in the same .o; the IRON-Python topology links
// them in based on the variant flag at lower-time.

#include <cstdint>
#include <cstring>

// v0.5 vectorized inner loop. Gate on the Peano-emitted AIE arch macro
// so host-side source checks and scalar emulation builds do not require
// AIE API headers.
#if defined(__AIE_ARCH__) && !defined(BIONPU_FORCE_SCALAR)
#  define BIONPU_HAS_AIE_API 1
#  include <aie_api/aie.hpp>
#else
#  define BIONPU_HAS_AIE_API 0
#endif

#ifndef BIONPU_BERT_M
#define BIONPU_BERT_M 47
#endif
#ifndef BIONPU_BERT_K
#define BIONPU_BERT_K 768
#endif
#ifndef BIONPU_BERT_N
#define BIONPU_BERT_N 2
#endif
// qkvo row-slab sizes. With M=47 and N_TILES=4, M pads to 48 and each
// tile owns 12 rows. K_CHUNK=8 keeps the full N=768 weight slab plus
// scales inside tile DM.
#ifndef BIONPU_BERT_N_TILES
#define BIONPU_BERT_N_TILES 4
#endif
#ifndef BIONPU_BERT_K_CHUNK
#define BIONPU_BERT_K_CHUNK 8
#endif

// Symbol-name token-pasting for the head-style entry point. The
// IRON-Python topology binds `bert_int8_matmul_<N>` (where <N> = the
// build-time BIONPU_BERT_N), and the function below uses the same
// pasted name so a single source compile lands the symbol the IRON
// Kernel() resolver expects.
#define BIONPU_PASTE_HEAD_NAME(N) bert_int8_matmul_##N
#define BIONPU_HEAD_NAME(N)       BIONPU_PASTE_HEAD_NAME(N)
#define BIONPU_BERT_HEAD_SYMBOL   BIONPU_HEAD_NAME(BIONPU_BERT_N)

namespace {

// Saturating int8 cast. AIE2P has hardware saturate ops we'll use
// in v0.5; scalar version below is deliberately portable so the
// kernel can also build on host emulation.
inline int8_t saturate_int8(int32_t v) {
    if (v >  127) return  127;
    if (v < -128) return -128;
    return static_cast<int8_t>(v);
}

// f32 round-half-away-from-zero, manual.
//
// The "obvious" `__builtin_nearbyintf` crashes the Peano AIE2P GISel
// Legalizer in this version of llvm-aie (memory: similar issues with
// scalar-FP32 round-to-int ops surface in BM-spill paths). Hand-rolled
// add-half-then-truncate sidesteps that legalization rule entirely
// and lowers cleanly.
//
// Tie-handling difference vs nearbyintf (round-half-to-even) is
// strictly bounded — at most 1 LSB of the i8 output, well inside the
// 1 ULP byte-equivalence tolerance the verify harness allows.
inline int32_t round_nearest_int32(float v) {
    return v >= 0.0f
        ? static_cast<int32_t>(v + 0.5f)
        : static_cast<int32_t>(v - 0.5f);
}

inline int32_t dot_i8_scalar(
    const int8_t * __restrict__ x,
    const int8_t * __restrict__ w,
    int k_len
) {
    int32_t acc = 0;
    for (int k = 0; k < k_len; ++k) {
        acc += static_cast<int32_t>(x[k]) * static_cast<int32_t>(w[k]);
    }
    return acc;
}

// AIE2P v0.5 perf path: reduce the INT8 dot product with AIE-API vector
// MACs, then horizontally sum the INT32 lanes. The scalar fallback keeps
// the same source usable for host checks and non-Peano builds.
inline int32_t dot_i8(
    const int8_t * __restrict__ x,
    const int8_t * __restrict__ w,
    int k_len
) {
#if BIONPU_HAS_AIE_API
    constexpr int VEC_I8 = 16;
    aie::accum<acc32, VEC_I8> acc;
    acc.from_vector(aie::broadcast<int32_t, VEC_I8>(0));

    int k = 0;
    for (; k + VEC_I8 <= k_len; k += VEC_I8) {
        aie::vector<int8, VEC_I8> x_v = aie::load_v<VEC_I8>(x + k);
        aie::vector<int8, VEC_I8> w_v = aie::load_v<VEC_I8>(w + k);
        acc = aie::mac(acc, w_v, x_v);
    }

    auto lanes = acc.to_vector<int32_t>();
    int32_t sum = 0;
    for (int i = 0; i < VEC_I8; ++i) {
        sum += lanes.get(i);
    }
    if (k < k_len) {
        int8 x_tail[VEC_I8] = {};
        int8 w_tail[VEC_I8] = {};
        for (int i = 0; k < k_len; ++i, ++k) {
            x_tail[i] = x[k];
            w_tail[i] = w[k];
        }
        aie::vector<int8, VEC_I8> x_v = aie::load_v<VEC_I8>(x_tail);
        aie::vector<int8, VEC_I8> w_v = aie::load_v<VEC_I8>(w_tail);
        aie::accum<acc32, VEC_I8> tail_acc;
        tail_acc.from_vector(aie::broadcast<int32_t, VEC_I8>(0));
        tail_acc = aie::mac(tail_acc, w_v, x_v);
        auto tail_lanes = tail_acc.to_vector<int32_t>();
        for (int i = 0; i < VEC_I8; ++i) {
            sum += tail_lanes.get(i);
        }
    }
    return sum;
#else
    return dot_i8_scalar(x, w, k_len);
#endif
}

}  // namespace

extern "C" {

// ──────────────────────────────────────────────────────────────────────────
// Head-style single-tile INT8 matmul.
//
// Used by:
//   v0.4-alpha — DNABERT-Epi classifier head (M=47, K=768, N=2)
//   step 0.3b  — Q·Kᵀ per-head    (M=47, K=64,  N=47)
//                scores·V per-head (M=47, K=47, N=64)  — see SCOPE-1 note
//                                  on the K=47 alignment caveat
//
// Symbol name: `bert_int8_matmul_<BIONPU_BERT_N>` via token paste so a
// single .cc compile produces the correct symbol for the build's N.
// ──────────────────────────────────────────────────────────────────────────

// Single-tile INT8 matmul. The per-output `combined` scale already
// folds (input_scale * weight_scale[n]) / output_scale at calibration
// time on the host (see bionpu.scoring.quantize); the bias passes
// through unchanged.
//
// Inputs:
//   x:        M × K   int8 row-major
//   ws_buf:   N*K + (N+1)*4 bytes — int8 weights followed by float32 scales.
//             The 3-input-fifo design (x, w, scales separately) doesn't
//             fit AIE2P's 2-in / 2-out CoreTile DMA budget; w + scales
//             concatenate at the host into a single byte buffer.
//             Layout:
//               ws_buf[0 .. N*K - 1]                   = int8 weights (N×K)
//               ws_buf[N*K .. N*K + (N+1)*4 - 1]       = float32 scales (N+1)
// Output:
//   y:        M × N int8 row-major
void BIONPU_BERT_HEAD_SYMBOL(
    const int8_t * __restrict__ x,
    const int8_t * __restrict__ ws_buf,
          int8_t * __restrict__ y
) {
    constexpr int M = BIONPU_BERT_M;
    constexpr int K = BIONPU_BERT_K;
    constexpr int N = BIONPU_BERT_N;

    const int8_t *w      = ws_buf;
    const float  *scales = reinterpret_cast<const float *>(ws_buf + N * K);

    // For each output cell: i32 accumulator over the K reduction.
    // On AIE2P this lowers to AIE-API vector MACs; host builds take the
    // scalar fallback through the same helper.
    for (int m = 0; m < M; ++m) {
        const int8_t *x_row = x + m * K;
        for (int n = 0; n < N; ++n) {
            const int8_t *w_row = w + n * K;
            const int32_t acc = dot_i8(x_row, w_row, K);
            // Fused scale + INT8 saturate. The host's
            // bionpu.scoring.quantize sets `combined[n]` such that
            // y_int8 ≈ round(W_fp · x_fp / output_scale), preserving
            // the byte-equivalence contract.
            const float fy = static_cast<float>(acc) * scales[n];
            y[m * N + n] = saturate_int8(round_nearest_int32(fy));
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────
// v0.4-beta — qkvo specialization (M=47, K=768, N=768).
//
// Each compute tile owns M_PER_TILE padded token rows and all output
// channels. The K loop runs in IRON-Python; this kernel's three entry points handle
// init / accumulate / finalize:
//
//   init()       — zero the static INT32 accumulator
//   acc()        — i32 += i8×i8 over one K_CHUNK slab
//   finalize()   — fused-scale + INT8 saturate of acc → y_part
//
// The accumulator is a tile-local static array (private to each tile's
// kernel image — IRON places the same .o on all four tiles, but each
// tile's static memory is independent).
// ──────────────────────────────────────────────────────────────────────────

namespace {

constexpr int QKVO_M           = BIONPU_BERT_M;                          // 47
constexpr int QKVO_M_PAD       =
    ((BIONPU_BERT_M + BIONPU_BERT_N_TILES - 1) / BIONPU_BERT_N_TILES)
    * BIONPU_BERT_N_TILES;                                               // 48
constexpr int QKVO_M_PER_TILE  = QKVO_M_PAD / BIONPU_BERT_N_TILES;       // 12
constexpr int QKVO_K_CHUNK     = BIONPU_BERT_K_CHUNK;                    // 8
constexpr int QKVO_N           = BIONPU_BERT_N;                          // 768
constexpr int QKVO_SCALES_N    = BIONPU_BERT_N + 1;                      // 769

}  // namespace

// Zero the i32 accumulator.
//
// Inputs:
//   acc_buf:    M_PER_TILE × N int32 — tile-local IRON Buffer
void bert_int8_matmul_qkvo_init(
          int32_t * __restrict__ acc_buf
) {
    for (int i = 0; i < QKVO_M_PER_TILE * QKVO_N; ++i) {
        acc_buf[i] = 0;
    }
}

// One K_CHUNK slab of the matmul.
//
// Inputs:
//   xs_chunk:   byte buffer of size M*K_CHUNK + (N+1)*4 bytes:
//                 [0          .. M*K_CHUNK - 1]            = x int8 (M × K_CHUNK)
//                 [M*K_CHUNK  .. M*K_CHUNK + (N+1)*4 - 1]  = scales fp32 (N+1)
//               The host duplicates the scales prefix on every chunk to
//               keep ObjectFifo elements uniform-size.
//   w_chunk:    N × K_CHUNK int8 row-major (N-major, K_CHUNK-minor)
//   acc_buf:    M_PER_TILE × N int32 — tile-local IRON Buffer (read/write)
//   scales_buf: (N + 1) float32 — tile-local IRON Buffer.
//               This kernel re-stashes the full per-output scale vector
//               every call; only the LAST call's write matters since
//               finalize reads it after the K loop.
//   tile_idx:   0..N_TILES-1 — selects which M_PER_TILE row slab this
//               tile owns.
//
// Effect:
//   acc_buf[m_local * N + n] += sum_k x_chunk[m_global, k] * w_chunk[n, k]
//   scales_buf[0..N] = *(float*)(xs_chunk + M*K_CHUNK)
void bert_int8_matmul_qkvo_acc(
    const int8_t * __restrict__ xs_chunk,
    const int8_t * __restrict__ w_chunk,
          int32_t * __restrict__ acc_buf,
          float   * __restrict__ scales_buf,
          int32_t                tile_idx
) {
    constexpr int M  = QKVO_M;
    constexpr int N  = QKVO_N;
    constexpr int Mp = QKVO_M_PER_TILE;
    constexpr int Kc = QKVO_K_CHUNK;

    // Stash the full scales vector. Cost: 769*4 per K_CHUNK; acceptable
    // for this scalar correctness path and keeps finalize local.
    {
        const float *full =
            reinterpret_cast<const float *>(xs_chunk + M * Kc);
        for (int i = 0; i < N + 1; ++i) {
            scales_buf[i] = full[i];
        }
    }

    const int8_t *x_chunk = xs_chunk;  // x lives at the head of xs_chunk

    const int row0 = tile_idx * Mp;
    for (int ml = 0; ml < Mp; ++ml) {
        const int mg = row0 + ml;
        int32_t *ar = acc_buf + ml * N;
        if (mg >= M) {
            continue;
        }
        const int8_t *xr = x_chunk + mg * Kc;
        for (int n = 0; n < N; ++n) {
            const int8_t *wr = w_chunk + n * Kc;
            ar[n] += dot_i8(xr, wr, Kc);
        }
    }
}

// Fused-scale + INT8 saturate of the accumulator into the int8 output.
//
// Inputs:
//   acc_buf:    M_PER_TILE × N int32 — read-only at this stage
//   scales_buf: N+1 float32 — full scale vector (read-only)
//   y_part:     M_PER_TILE × N int8 row-major (output)
void bert_int8_matmul_qkvo_finalize(
    const int32_t * __restrict__ acc_buf,
    const float   * __restrict__ scales_buf,
          int8_t  * __restrict__ y_part
) {
    constexpr int Mp = QKVO_M_PER_TILE;
    constexpr int N  = QKVO_N;

    for (int m = 0; m < Mp; ++m) {
        const int32_t *ar = acc_buf + m * N;
              int8_t  *yr = y_part  + m * N;
        for (int n = 0; n < N; ++n) {
            const float fy = static_cast<float>(ar[n]) * scales_buf[n];
            yr[n] = saturate_int8(round_nearest_int32(fy));
        }
    }
}

}  // extern "C"
