#!/usr/bin/env bash
# bionpu — AIE2P-accelerated genomics with reference-equivalence verification.
# Copyright (C) 2026 OpenSensor / Matt Davis <matt@opensensor.io>
# GPL-3.0-or-later. See ../LICENSE.
#
# Make per-device energy counters visible to the bench harness on this host.
#
# Two surfaces:
#   1. RAPL (CPU package energy) at /sys/class/powercap/*/energy_uj.
#      Stock Ubuntu/Debian ship these mode 0400 as a side-channel
#      mitigation. We chmod them world-readable AND persist that via
#      /etc/tmpfiles.d so it survives reboot.
#   2. xrt-smi (NPU energy) at /opt/xilinx/xrt/bin/xrt-smi. The vendor
#      build is amdxdna-aware and enumerates AIE2P devices; the Ubuntu
#      libxrt-utils build at /usr/bin/xrt-smi does not. The bench
#      probe already prefers the vendor path; this script only checks
#      that it exists.
#
# Re-runnable: idempotent, only writes if state differs.
# Requires: sudo. Refuses to act otherwise (rather than silently failing).

set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "host-energy-setup: must be run as root (try: sudo $0)" >&2
  exit 1
fi

TMPFILES_CONF="/etc/tmpfiles.d/bionpu-rapl.conf"
RAPL_GLOB="/sys/class/powercap/*/energy_uj"

echo "host-energy-setup: AIE2P bench harness energy-counter setup"
echo

# -----------------------------------------------------------------------------
# 1. RAPL chmod (runtime + persistence)
# -----------------------------------------------------------------------------
shopt -s nullglob
rapl_files=( $RAPL_GLOB )
shopt -u nullglob

if (( ${#rapl_files[@]} == 0 )); then
  echo "[1/2] RAPL: no energy_uj files at $RAPL_GLOB"
  echo "      The intel_rapl_msr / amd_energy modules may not be loaded."
  echo "      Try: modprobe intel_rapl_msr"
  echo "      If the modules don't exist, the kernel build doesn't"
  echo "      include them and CPU energy stays UNAVAILABLE per"
  echo "      POWER_DOMAINS.md §1.4 (which is fine — bench falls back"
  echo "      to RaplStub with energy_source=stub)."
else
  echo "[1/2] RAPL: ${#rapl_files[@]} energy_uj file(s) found"
  for f in "${rapl_files[@]}"; do
    cur_mode=$(stat -c '%a' "$f")
    if [[ "$cur_mode" == "444" || "$cur_mode" == "644" ]]; then
      echo "      $f (mode $cur_mode — already readable)"
    else
      chmod a+r "$f"
      new_mode=$(stat -c '%a' "$f")
      echo "      $f (mode $cur_mode → $new_mode)"
    fi
  done
  # Persist via /etc/tmpfiles.d so the chmod survives reboot.
  expected_conf=$(cat <<'EOF'
# bionpu RAPL energy-counter visibility
# Generated by tools/host-energy-setup.sh.
# Ubuntu/Debian ship these mode 0400 as a side-channel mitigation;
# the bench harness needs world-read for unprivileged invocation.
# POWER_DOMAINS.md §1.4: explicit, persisted, auditable.
z /sys/class/powercap/intel-rapl:0/energy_uj  0444 - - -
z /sys/class/powercap/intel-rapl:0:0/energy_uj 0444 - - -
EOF
)
  if [[ -f "$TMPFILES_CONF" ]] && cmp -s <(echo "$expected_conf") "$TMPFILES_CONF"; then
    echo "      Persisted: $TMPFILES_CONF (already up-to-date)"
  else
    if [[ -f "$TMPFILES_CONF" ]]; then
      backup="${TMPFILES_CONF}.bak.$(date +%Y%m%d-%H%M%S)"
      cp "$TMPFILES_CONF" "$backup"
      echo "      Backed up existing: $backup"
    fi
    echo "$expected_conf" > "$TMPFILES_CONF"
    echo "      Persisted: $TMPFILES_CONF"
  fi
fi
echo

# -----------------------------------------------------------------------------
# 2. xrt-smi sanity check
# -----------------------------------------------------------------------------
VENDOR_XRT="/opt/xilinx/xrt/bin/xrt-smi"
if [[ -x "$VENDOR_XRT" ]]; then
  ver=$("$VENDOR_XRT" --version 2>/dev/null | awk '/Version/ { print $3; exit }')
  echo "[2/2] xrt-smi: vendor build at $VENDOR_XRT (XRT $ver)"
  if "$VENDOR_XRT" examine 2>/dev/null | grep -q "aie2p"; then
    echo "      AMD NPU enumerated: OK"
  else
    echo "      AMD NPU NOT enumerated by vendor xrt-smi —"
    echo "      check that the amdxdna driver is loaded (lsmod | grep amdxdna)"
    echo "      and the device is at /dev/accel/accel0."
  fi
else
  echo "[2/2] xrt-smi: vendor build not found at $VENDOR_XRT"
  echo "      Install xrt_plugin-amdxdna from the vendor bundle, or"
  echo "      set BIONPU_XRT_SMI=/path/to/amdxdna-aware/xrt-smi."
  echo "      The Ubuntu libxrt-utils package at /usr/bin/xrt-smi"
  echo "      does NOT support AMD NPU enumeration."
fi
echo

echo "host-energy-setup: done. Verify with:  bionpu bench probe"
